# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-angelfish

# >> macros
# << macros

Summary:    AngelFish Health Monitor
Version:    1.0
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        https://github.com/aebruno/angelfish
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-angelfish.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(bluez)
BuildRequires:  cmake
BuildRequires:  desktop-file-utils

%description
AngelFish Health Monitor application.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
rm -rf rpmbuilddir
mkdir rpmbuilddir
cd rpmbuilddir &&  cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr ..
cd ..
make -C rpmbuilddir -j VERBOSE=1 %{?_smp_mflags}
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
DESTDIR=%{buildroot} make -C rpmbuilddir install
mkdir -p %{_bindir}
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# >> files
# << files

%post
if [ -x /usr/sbin/setcap ]; then
    setcap 'cap_net_raw,cap_net_admin=eip' /usr/bin/harbour-angelfish
fi
